version: 2

updates:
  - package-ecosystem: npm
    directory: '/javascript'
    labels:
    - 'automerge'
    schedule:
      interval: daily
    open-pull-requests-limit: 4

  - package-ecosystem: npm
    directory: '/javascript/packages/cli'
    labels:
    - 'automerge'
    schedule:
      interval: daily
    open-pull-requests-limit: 4

  - package-ecosystem: npm
    directory: '/javascript/packages/orchestrator'
    labels:
    - 'automerge'
    schedule:
      interval: daily
    open-pull-requests-limit: 4

  - package-ecosystem: npm
    directory: '/javascript/packages/utils'
    labels:
    - 'automerge'
    schedule:
      interval: daily
    open-pull-requests-limit: 4

  - package-ecosystem: github-actions
    directory: '/'
    labels:
    - 'automerge'
    schedule:
      interval: daily
