queue_rules:
  - name: default
    conditions:
      - check-success=all
      - check-success=continuous-integration/gitlab-publish-docker-pr
      - check-success=continuous-integration/gitlab-build
      - check-success=continuous-integration/gitlab-lint
      - check-success=continuous-integration/gitlab-package
      - check-success=continuous-integration/gitlab-publish-test
      - check-success=continuous-integration/gitlab-test
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - check-success=all
      - check-success=continuous-integration/gitlab-publish-docker-pr
      - check-success=continuous-integration/gitlab-build
      - check-success=continuous-integration/gitlab-lint
      - check-success=continuous-integration/gitlab-package
      - check-success=continuous-integration/gitlab-publish-test
      - check-success=continuous-integration/gitlab-test
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
        method: merge
