apiVersion: v1
kind: PersistentVolume
metadata:
  name: global-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: { storage }
  claimRef:
    name: global-data-pvc
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: { pdName }
    fsType: { fsType }
    readOnly: true
