apiVersion: v1
kind: ServiceAccount
metadata:
  name: zombie-internal-kubectl
#  namespace: {{namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-namespaces
#  namespace: {{namespace}}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-namespace-to-sa
#  namespace: {{namespace}}
subjects:
  - kind: ServiceAccount
    name: zombie-internal-kubectl
roleRef:
  kind: Role
  name: delete-namespaces
  apiGroup: rbac.authorization.k8s.io
