# some comment - next line is empty for testing parser

relaychain:
  default_image: 'docker.io/paritypr/polkadot-debug:master'
  default_command: polkadot
  default_args:
    - '-lparachain=debug'
  chain: rococo-local
  nodes:
    - name: alice
      validator: true
    - name: bob
      image: 'docker.io/paritypr/polkadot-debug:5236-0.9.18-c55660e9-be16bd72'
      validator: true
      args:
        - '--database=paritydb-experimental'