[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  image = "docker.io/paritypr/polkadot-debug:5236-0.9.18-c55660e9-be16bd72"
  validator = true
  args = ["--database=paritydb-experimental"]

[[parachains]]
id = 2000
cumulus_based = true
genesis_wasm_generator = "test-collator export-genesis-wasm"
genesis_state_generator = "test-collator export-genesis-state"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-collator:latest"
  command = "test-collator"
  args = ["-lparachain=debug"]