# This example will override the `polkadot` binary in each node with
# the provided in the `local_path` config of `global_overrides`.

[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "wococo-local"
command = "polkadot"

[[relaychain.global_overrides]]
local_path = "../bins/polkadot"
remote_name = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--bob", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "--charlie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  extra_args = ["--dave", "-lparachain=debug"]

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"
  args = ["-lparachain=debug"]
