[settings]
timeout = 666

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
[default_delay_network_settings]
  latency =  "200ms"
  
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  [[delay_network_settings]]
    latency =  "200ms"
  

  [[relaychain.nodes]]
  name = "bob"
  validator = true
    

[[parachains]]
id = 100

  [[parachains.collator_groups]]
    count = 2
    [parachains.collator_groups.collator]
    name = "collator"
    command = "polkadot-parachain"
    image = "docker.io/parity/polkadot-parachain:latest"
    [[delay_network_settings]]
      latency =  "4000ms"
      jitter = "4000ms"
      correlation = "4000ms"