[settings]
timeout = 666

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"
[relaychain.default_delay_network_settings]
  latency =  "200ms"

  [[relaychain.nodes]]
  name = "alice"
  [relaychain.nodes.delay_network_settings]
    latency =  "1000ms"


  [[relaychain.nodes]]
  name = "bob"


[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
    [parachains.collator.delay_network_settings]
      latency =  "4000ms"
      jitter = "4000ms"
      correlation = "100"