[settings]
timeout = 1000
# provider = "Podman"

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]

[[parachains]]
id = 100
addToGenesis = true

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"