[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
default_substrate_cli_args_version = "2"

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  args = [
    "--database=paritydb-experimental", 
    "--base-path={{'network'|zombie('base_path')}}/alice-custom-data",
  ]

[[parachains]]
id = 100
default_substrate_cli_args_version = "2"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]
