# Example demonstrating HTTP/HTTPS URL support for chain_spec_path
# This shows how to use remote chain specs instead of local files

[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"
# Example using HTTPS URL for relaychain chain spec
chain_spec_path = "https://raw.githubusercontent.com/paritytech/polkadot/refs/tags/v1.0.0/node/service/chain-specs/rococo.json"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 100
# Example using HTTPS URL for parachain chain spec
chain_spec_path = "https://raw.githubusercontent.com/paritytech/cumulus/refs/heads/master/parachains/chain-specs/asset-hub-rococo.json"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]