apiVersion: v1
kind: Pod
metadata:
  name: tempo
  namespace: zombie-4ce106de
  labels:
    app.kubernetes.io/name: zombie-4ce106de
    app.kubernetes.io/instance: tempo
    zombie-role: tempo
    app: zombienet
    zombie-ns: zombie-4ce106de
spec:
  hostname: tempo
  containers:
    - image: docker.io/grafana/tempo:latest
      name: tempo
      args:
        - -config.file=/etc/tempo/tempo.yaml
      imagePullPolicy: Always
      ports:
        - containerPort: 14268
          name: jaeger_ingest
          hostPort: 34019
        - containerPort: 3100
          name: tempo
          hostPort: 45709
        - containerPort: 4317
          name: otlp_grpc
          hostPort: 36093
        - containerPort: 4318
          name: otlp_http
          hostPort: 45101
        - containerPort: 9411
          name: zipkin
          hostPort: 41203
      volumeMounts:
        - name: tempo-cfg
          mountPath: /etc/tempo
          readOnly: false
        - name: tempo-data
          mountPath: /data
          readOnly: false
  restartPolicy: OnFailure
  volumes:
    - name: tempo-cfg
      hostPath:
        type: Directory
        path: ./test-dir/tempo/etc
    - name: tempo-data
      hostPath:
        type: Directory
        path: ./test-dir/tempo/data
