apiVersion: v1
kind: Pod
metadata:
  name: temp-1
  namespace: zombie-4ce106de
  labels:
    zombie-role: full-node
    app: zombienet
    zombie-ns: zombie-4ce106de
    app.kubernetes.io/name: zombie-4ce106de
    app.kubernetes.io/instance: temp-1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9615"
spec:
  hostname: temp-1
  containers:
    - image: docker.io/parity/polkadot:latest
      name: temp-1
      imagePullPolicy: Always
      ports:
        - containerPort: 9615
          name: prometheus
          hostPort: 44671
        - containerPort: 9933
          name: rpc
          hostPort: 42193
        - containerPort: 9944
          name: rpc-ws
          hostPort: 40471
        - containerPort: 30333
          name: p2p
          hostPort: 45331
      env: []
      volumeMounts:
        - name: tmp-cfg
          mountPath: /cfg:U
          readOnly: false
        - name: tmp-data
          mountPath: /data:U
          readOnly: false
        - name: tmp-relay-data
          mountPath: /relay-data:U
          readOnly: false
      command:
        - bash
        - -c
        - polkadot build-spec --chain /cfg/rococo-local-plain.json
          --disable-default-bootnode  --raw > /cfg/rococo-local-raw.json
  initContainers: []
  restartPolicy: OnFailure
  volumes:
    - name: tmp-cfg
      hostPath:
        type: Directory
        path: ./test-dir/temp-1/cfg
    - name: tmp-data
      hostPath:
        type: Directory
        path: ./test-dir/temp-1/data
    - name: tmp-relay-data
      hostPath:
        type: Directory
        path: ./test-dir/temp-1/relay-data
