// CONSTANTS
const AVAILABLE_PROVIDERS = ["podman", "kubernetes", "native"];
const DEFAULT_BALANCE = 2000000000000;
const DEFAULT_GLOBAL_TIMEOUT = 1200; // 20 mins
const DEFAULT_PROVIDER = "kubernetes";

export {
  AVAILABLE_PROVIDERS,
  DEFAULT_BALANCE,
  DEFAULT_GLOBAL_TIMEOUT,
  DEFAULT_PROVIDER,
};
