apiVersion: v1
kind: Service
metadata:
  name: bootnode
spec:
  selector:
    zombie-role: bootnode
  ports:
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
