apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: monitoring
  name: delete-podmonitors
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["podmonitors"]
    verbs: ["get", "list", "delete"]