apiVersion: batch/v1
kind: CronJob
metadata:
  name: clr-podmtr-{{namespace}}
spec:
  schedule: "{{schedule}}"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: podmonitor-cleaner
    spec:
      template:
        spec:
          serviceAccountName: zombie-internal-kubectl
          containers:
            - name: podmonitor-cleaner-job
              image: bitnami/kubectl:1.17.3
              command:
                - "bin/bash"
                - "-c"
                - "kubectl delete podmonitor {{namespace}} -n monitoring"
          restartPolicy: Never
