apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internal-access
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - {{namespace}}
          - gitlab
          - loki
          - tempo
          - monitoring
          - parachain-exporter
  policyTypes:
  - Ingress