apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { name }
spec:
  accessModes:
    - { accessMode }
  storageClassName: cloning
  resources:
    requests:
      storage: { storage }
  dataSource:
    kind: PersistentVolumeClaim
    name: { source }
