metadata:
  name: node-data-volume-retain
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
parameters:
  type: pd-balanced
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
