metadata:
  name: node-data-volume
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
