apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { name }
spec:
  resources:
    requests:
      storage: { storage }
  accessModes:
    - ReadWriteOnce
  storageClassName: { storageClass }
