apiVersion: v1
kind: Service
metadata:
  name: telemetry
spec:
  selector:
    app: telemetry
  ports:
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
