apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-servicemonitor
  labels:
    app: metrics
spec:
  selector:
    matchLabels:
      app: metrics
  endpoints:
  - port: http-metrics
    interval: 15s
