name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install -g cspell
      - run: cd javascript && cspell .

  check-nix-hash:
    name: "Check nix hash is up-to-date"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Building the nix file"
        run: |
            echo "If the job is failing with: \"hash mismatch in fixed-output derivation\""
            echo "Copy the hash after \"got:\" and replace \"npmDepsHash\" in \"flake-module.nix\" with the hash"
            ! nix develop --command "exit 1" 2>&1 | grep "hash mismatch" -A2
