name: MD link checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: .github/markdown-link-checker-config.json
