name: Zombienet Packages Test Releases

on:
  push:
    branches: [nik-fix-axios]

jobs:
  test_release_for_linux:
    name: build_release_for_linux
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
      - run: npm run package
      - name: test zombienet-linux
        run: ./bins/zombienet-linux version
  test_release_for_mac:
    name: build_release_for_mac
    needs: test_release_for_linux
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
      - run: npm run package
      - name: test zombienet-mac
        run: ./bins/zombienet-linux version
