[relaychain]
default_image = "paritypr/synth-wave:3639-0.9.9-7edc6602-ed5fb773"
chain = "polkadot-local"
command = "polkadot"
timeout = "1000"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  commandWithArgs = "/usr/local/bin/malus back-garbage-candidate --bob -lparachain=debug"
  image = "paritypr/malus:3639-7edc6602"
  autoConnectApi = false


  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  commandWithArgs = "/usr/local/bin/malus back-garbage-candidate --charlie -lparachain=debug"
  image = "paritypr/malus:3639-7edc6602"
  autoConnectApi = false


  [[relaychain.nodes]]
  name = "david"
  validator = true
  commandWithArgs = "/usr/local/bin/malus back-garbage-candidate --dave -lparachain=debug"
  image = "paritypr/malus:3639-7edc6602"
  autoConnectApi = false

  [[relaychain.nodes]]
  name = "eve"
  validator = true
  commandWithArgs = "/usr/local/bin/malus suggest-garbage-candidate --eve -lparachain=debug"
  image = "paritypr/malus:3639-7edc6602"
  autoConnectApi = false

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  commandWithArgs = "/usr/local/bin/adder-collator -lparachain=debug --chain /cfg/polkadot-local.json --port 30333 --no-mdns --bootnodes /dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"